import localFont from "next/font/local";
import "./globals.css";

const poppinsSemi = localFont({
  src: "./fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins-semi",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppinsSemi.variable}`}>{children}</body>
    </html>
  );
}
